version: '2.1'

services:
  app:
    restart: always
    build: ./function-as-a-service
    ports:
      - "3034:3034"
    volumes:
      - datavolume:/tmp
    command: /usr/local/bin/gunicorn -w 2 -b :3034 wsgi
    links:
      - mongo
      - kafkaserver
    depends_on:
      kafkaserver:
        condition: service_healthy
      mongo:
        condition: service_healthy

  sourceapp:
    restart: always
    build: ./source-service
    ports:
      - "5000:5000"
    volumes:
      - /home/flask/source-service/web
    command: /usr/local/bin/gunicorn -w 2 -b :5000 wsgi
    links:
      - mongo
      - kafkaserver
    depends_on:
      mongo:
        condition: service_healthy
      kafkaserver:
        condition: service_healthy

  listener:
    build: ./function-as-a-service
    ports:
      - "3035:3035"
    volumes:
      - datavolume:/tmp
    command: bash -c "cd listener/ && python -u listener.py"
    links:
      - mongo
      - kafkaserver
    depends_on:
      mongo:
        condition: service_healthy
      kafkaserver:
        condition: service_healthy

  mongo:
    image: mongo:3.6.0
    ports:
        - "27017:27017"
    environment:
      MONGODB_DATABASE: "faas"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 12

  apache2:
    build: ./webapp
    volumes:
        - /usr/local/apache2/htdocs/
    ports:
        - 80:80
        - 443:443

  kafkaserver:
    image: wurstmeister/kafka:0.10.1.0-2
    hostname: kafkaserver
    ports:
      - "9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafkaserver"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "Topic1:1:1:compact"
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

volumes:
  datavolume: {}